### ISSUE TITLE
In flut mux simulation why is the delay measured from the flut input to the carry chain mux output?

### ISSUE THREAD

**Issue by MohamedEldafrawy** [vaughnbetz/COFFE#19]
https://github.com/vaughnbetz/COFFE/blob/7b407abe9fbbfa5ec5afa4b39aca344af62433ef/coffe/top_level.py#L4701-L4708

https://github.com/vaughnbetz/COFFE/blob/7b407abe9fbbfa5ec5afa4b39aca344af62433ef/coffe/top_level.py#L4719-L4726

In case of FLUT simulation with carry chains, why is the total delay of the flut mux measured from the input of the flut to the output of the carry chain mux. Shouldn't it be from n_1_1 to n_1_3?

![selection_006](https://user-images.githubusercontent.com/35947424/42424212-5b8e6950-82d6-11e8-818b-f94c66fce606.png)

**Comment by sadegh68** [comment]
The mentioned delay is meant to show the delay of the last stage of the LUT. You are right, the naming of the variables can be changed to make it easier to understand. Alternatively, one can measure the delay of those two components separately and add them up.
