### ISSUE TITLE
About the architecture description xml file exported by COFFE cannot be synthesized by OdinII in VTR

### ISSUE THREAD

**Issue by jdzhu19** [vaughnbetz/COFFE#44]
Hi,

I am trying to use COFFE2(master branch) to output the architecture description XML file and use it as input to VTR8, but there is an error reported in the process as shown in the attachment, and it shows that there are some problems with the generated architecture description file.

<img width="851" alt="1676462056634" src="https://user-images.githubusercontent.com/69670945/219021483-5aff42cf-5656-4dfd-a383-816c457b21f9.png">

After doing some troubleshooting I found the error in the odin.out generated by VTR :
`Odin Failed to load architecture file: Unexpected attribute 'capacity' found on node 'pb_type'. Expected (possibly) one of: 'name'. with exit code4`
I think this is caused by the `<pb_type name="io" capacity="8">` in the generated architecture file, and for VTR, capacity is not a required or optional attribute of pb_type. And there are many problems with attributes like this, I guess it's because the output architecture file lacks a description of the tile because after comparing the existing architecture files in VTR I found that coffe/vpr.py, which is used by COFFE to print architecture files, is missing many descriptions of tiles comparing from existing architecture files in VTR. By the way, the architecture file I generated with COFFE seems to have problems with the delay_matrix (all 0), I think this may also be abnormal. I have put the XML in the attached zip file, and I've also put odin.out and some other output of the VTR in the zip file, please check it.

[vtr_output.zip](https://github.com/vaughnbetz/COFFE/files/10742795/vtr_output.zip)

This may also mean that the current COFFE output architecture files don't seem to be compatible with what VTR needs, which is not consistent with what I've seen in some related papers, so I'd like to ask how to solve this problem.

Thank you for your time, and I'm looking forward to your answer!

**Comment by vaughnbetz** [comment]
Can you try it with the current vtr master branch? It sounds like COFFE is outputting a more recent arch file format than version 8.0.

@StephenMoreOSU : did you test vtr arch file output after your recent updates?

**Comment by Symbol2020z** [comment]
> Can you try it with the current vtr master branch? It sounds like COFFE is outputting a more recent arch file format than version 8.0.
> 
> @StephenMoreOSU : did you test vtr arch file output after your recent updates?
I haven't tried the latest VTR yet, my version of VTR was downloaded about last month, would this be a problem? Anyway I will try the latest version later.

**Comment by vaughnbetz** [comment]
The latest version must be downloaded directly from github; it is not the 8.0 release.

**Comment by StephenMoreOSU** [comment]
> Can you try it with the current vtr master branch? It sounds like COFFE is outputting a more recent arch file format than version 8.0.
> 
> @StephenMoreOSU : did you test vtr arch file output after your recent updates?

I actually didn't test the VTR output on the most recent updates, will test that when I get the chance

**Comment by jdzhu19** [comment]
I have downloaded the latest VTR master branch, but unfortunately, it still triggers the same error, and also, the "VTR8" I mentioned in my question actually refers to the version I downloaded from the master branch last month, however, it doesn't seem to be the key to solving the problem. If possible please check whether the current latest version of COFFE output architecture description file is available as the input on the current latest version of VTR, or whether there is any solution to achieve this purpose.

Thank you for your time, and I'm looking forward to your answer!

**Comment by jdzhu19** [comment]
> The latest version must be downloaded directly from github; it is not the 8.0 release.

I have downloaded the latest VTR master branch, but unfortunately, it still triggers the same error, and also, maybe I didn't make myself clear, the "VTR8" I mentioned in my question actually refers to the version I downloaded from the master branch last month, however, it doesn't seem to be the key to solving the problem. 

If possible please check whether the current latest version of COFFE output architecture description file is available as the input on the current latest version of VTR, or whether there is any solution to achieve this purpose.

Thank you for your time, and I'm looking forward to your answer!

**Comment by jdzhu19** [comment]
> The latest version must be downloaded directly from github; it is not the 8.0 release.

Besides, I would like to ask if there is a quick manual fix solution. And you know, maybe it's because the COFFE version is too new, so is there an old branch that can be used to interface with the latest VTR?

**Comment by vaughnbetz** [comment]
You could check out an older revision and try that.  There was a lot of refactoring over the past few months; taking something from Sept. 2022 or so would be good to try.

**Comment by jdzhu19** [comment]
> You could check out an older revision and try that. There was a lot of refactoring over the past few months; taking something from Sept. 2022 or so would be good to try.

Hi, you mentioned in your last reply that the architecture description file output from the Sept. 2022 version will probably be available, since I didn't directly find the September version in the branch but only the sm_asic_flow from last October and the innovus_support from November, I first tried the October branch, but I found that it used encounter, and since I only have innovus, I tried to change the encounter version branch to the innovus version branch published in November for convenience, and successfully ran through it, but first of all, I noticed that this version is much slower than this year's version to run through the no_sizing process, from 13min to nearly 3 hours, I don't know if this is normal or not, and secondly, the architecture files it outputs are similar to this year's version and are not available for the latest VTR. So I would like to ask specifically which commit version of some branch is determined to produce the architecture description file that is applicable to the current VTR?

Thank you for your time, and I'm looking forward to your answer!

**Comment by jdzhu19** [comment]
> You could check out an older revision and try that. There was a lot of refactoring over the past few months; taking something from Sept. 2022 or so would be good to try.

I mean, whatever it is the version using encounter or innovus, this EDA tool issue will be solved by myself.

**Comment by StephenMoreOSU** [comment]
@jdzhu19 The pnr runtime increased probably as I was trying to increase the QoR at the time, I need to add an option for express pnr runs to reduce the runtime, I'll open up an issue for that.
