### ISSUE TITLE
Failed to update delay(hspice failed to run)

### ISSUE THREAD

**Issue by YY246** [vaughnbetz/COFFE#57]
![image](https://github.com/vaughnbetz/COFFE/assets/83024091/d052fbf7-6cb5-4fbe-97cd-afc92543669b)

**Comment by StephenMoreOSU** [comment]
Similarly as in #58 I think this is related to you trying to run on Windows rather than Linux or not having the HSPICE tool downloaded and on your path.

**Comment by StephenMoreOSU** [comment]
Closing this due to COFFE's lack of windows support (and no intention of adding windows support)
